### PR TITLE
Correct processing of multiple, consecutive, LTCTI and maneuver event…

### PR DESCRIPTION
**Pull request by Gregg140**
…s during long shutdowns.

### CODE REVIEW

**Comment by jeanconn** [comment]
I'm still probably not the target audience for code review for this, but I could use a small overview of what doesn't work and how this fixes it in the PR text.

**Comment by jeanconn** [comment]
Is this PR still being considered?

**Comment by Gregg140** [comment]
I think it has to be eliminated.

**Review by jeanconn — CHANGES_REQUESTED** [review]
Looks like this PR should be closed then.

**Pull request closed without merging**
